#!/usr/bin/env bash

FODTFILE="$1"
xsltproc - "$FODTFILE" <<XSLT
<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0">
    <xsl:output method="text"/>
    <xsl:template match="text:p|text:h">
        <xsl:value-of select="."/>
        <xsl:text>&#10;</xsl:text>
    </xsl:template>
    <xsl:template match="text()"/>
</xsl:stylesheet>
XSLT
